#ifndef CORE_CONFIG_HPP
#define CORE_CONFIG_HPP

#define WINDOW_TITLE "Space Escape"
#define WINDOW_WIDTH 160
#define WINDOW_HEIGHT 152

#define PTM_RATIO 32.0
#define VELOCITY_ITERATIONS 6
#define POSITION_ITERATIONS 2

#define LEVEL_WIDTH 10
#define LEVEL_HEIGHT 20

#define WALL_THICKNESS 6

#define STATUS_WIDTH 48

#define BALL_WIDTH 4
#define BALL_HEIGHT 4

#define BRICK_WIDTH 10
#define BRICK_HEIGHT 6

#define PADDLE_WIDTH 20
#define PADDLE_HEIGHT 6
#define PADDLE_DELTA_VELOCITY 5

#define GLYPH_WIDTH 8
#define GLYPH_HEIGHT 8

#define COLOR_MAIN 187, 1, 252
#define COLOR_ACTIVE_1 128, 207, 1
#define COLOR_ACTIVE_2 1, 128, 207
#define COLOR_ACTIVE_3 207, 187, 1

#define SCREEN_WIDTH (WINDOW_WIDTH - STATUS_WIDTH)
#define SCREEN_HEIGHT (WINDOW_HEIGHT)

#endif