#ifndef CORE_CONFIG_HPP
#define CORE_CONFIG_HPP

#define WINDOW_TITLE "Space Escape"
#define WINDOW_WIDTH 160
#define WINDOW_HEIGHT 152

#define PTM_RATIO 32.0
#define VELOCITY_ITERATIONS 6
#define POSITION_ITERATIONS 2

#define WALL_THICKNESS 6

#define STATUS_WIDTH 48

#define BALL_WIDTH 4
#define BALL_HEIGHT 4
#define BALL_BOTTOM_OFFSET 24

#define BRICK_WIDTH 10
#define BRICK_HEIGHT 6
#define BRICK_TOP_OFFSET 36

#define PADDLE_WIDTH 20
#define PADDLE_HEIGHT 6
#define PADDLE_DELTA_VELOCITY 5
#define PADDLE_BOTTOM_OFFSET 12

#define GLYPH_WIDTH 8
#define GLYPH_HEIGHT 8

#define ROUND_MESSAGE_BOTTOM_OFFSET 64

#define SCREEN_WIDTH (WINDOW_WIDTH - STATUS_WIDTH)
#define SCREEN_HEIGHT (WINDOW_HEIGHT)

#endif