name: integration

on:
  push:
    branches: trunk
  pull_request:
    branches: trunk

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, cc: gcc }
          - { os: windows-latest, cc: cl }
          - { os: macos-latest, cc: clang }
    env:
      CC: ${{ matrix.config.cc }}
      CONFIG: Debug
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: build
          key: ${{ matrix.config.os }}-${{ hashFiles('CMakeLists.txt', 'cmake/**') }}
      - run: sudo apt-get update && sudo apt-get install xorg-dev libglu1-mesa-dev
        if: matrix.config.os == 'ubuntu-latest'
      - run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.CONFIG }}
      - run: cmake --build build --config ${{ env.CONFIG }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.config.os }}
          path: build/space-escape*