name: integration

on:
  push:
    branches: trunk
  pull_request:
    branches: trunk

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { os: ubuntu-latest, cc: gcc }
          - { os: windows-latest, cc: cl }
          - { os: macos-latest, cc: clang }
    env:
      BUILD_TYPE: Debug
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: build
          key: ${{ runner.os }}-${{ hashFiles('conanfile.txt', 'CMakeLists.txt') }}
      - uses: turtlebrowser/get-conan@main
      - run: sudo apt-get install libegl-dev
        if: matrix.config.os == 'ubuntu-latest'
      - run: conan profile new default --detect && conan profile update settings.compiler.libcxx=libstdc++11 default
        if: matrix.config.cc == 'gcc'
      - run: conan remote add bincrafters https://bincrafters.jfrog.io/artifactory/api/conan/public-conan
      - run: conan config set general.revisions_enabled=1
      - run: conan install . -if build -s build_type=${{ env.BUILD_TYPE }}
      - run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}
      - run: cmake --build build --config ${{ env.BUILD_TYPE }}
      - run: tar -cvf space-escape.tar -C build/bin .
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-${{ env.BUILD_TYPE }}
          path: space-escape.tar
